
import { PortfolioItem } from './types';

const photo = (file: string) => new URL(`./sitephotos/${file}`, import.meta.url).href;

export const allProjects: PortfolioItem[] = [
  { 
    id: '1', 
    title: 'ЭСТЕТИКА', 
    category: 'Art Gallery', 
    year: '2025', 
    imageUrl: photo('Эстетика.avif'),
    gallery: [photo('Эстетика.avif'), photo('Эстетика2.avif'), photo('Эстетика3.avif')],
    description: 'Минималистичная галерея современного искусства с AI-куратором',
    headline: 'Где искусство встречается с искусственным интеллектом — новый формат взаимодействия с коллекциями.',
    fullDescription: 'Платформа для ценителей искусства, объединяющая кураторские коллекции и интерактивный опыт. AI-историк искусства помогает погрузиться в мир каждого произведения, предоставляя глубокий контекст и персональные рекомендации. Плавная анимация скролла и продуманная типографика создают атмосферу элитной галереи.',
    technologies: ['React', 'Lenis', 'Tailwind CSS'],
    liveUrl: '#',
    duration: 6
  },
  { 
    id: '2', 
    title: 'FOCUSFLOW', 
    category: 'Digital Wellbeing', 
    year: '2025', 
    imageUrl: photo('focusflow.avif'),
    gallery: [photo('focusflow.avif'), photo('focusflow2.avif'), photo('focusflow3.avif'), photo('focusflow4.avif'), photo('focusflow5.avif'), photo('focusflow6.avif'), photo('focusflow7.avif'), photo('focusflow8.avif'), photo('focusflow9.avif')],
    description: 'Кинематографический опыт о цифровом благополучии с AI-коучем',
    headline: 'Интерактивная история о влиянии технологий на внимание — scrollytelling нового поколения.',
    fullDescription: 'Интерактивное путешествие через проблемы цифровой эпохи. Scrollytelling-формат раскрывает влияние технологий на наше внимание. Встроенный AI-коуч помогает выработать здоровые привычки, дыхательные упражнения и таймер фокусировки — всё для восстановления контроля над своим временем.',
    technologies: ['React', 'Intersection Observer', 'Web Audio API'],
    liveUrl: '#',
    duration: 8
  },
  { 
    id: '3', 
    title: "L'HOMME", 
    category: 'E-commerce', 
    year: '2025', 
    imageUrl: photo('l-homme.avif'),
    gallery: [photo('l-homme.avif'), photo('l-homme2.avif'), photo('l-homme3.avif'), photo('l-homme4.avif'), photo('l-homme5.avif'), photo('l-homme6.avif'), photo('l-homme7.avif'), photo('l-homme8.avif'), photo('l-homme9.avif')],
    description: 'Премиальный интернет-магазин мужской одежды',
    headline: 'Элегантность в каждом пикселе — e-commerce, отражающий философию сдержанной роскоши.',
    fullDescription: 'Элегантный e-commerce для современного мужчины. Минималистичный дизайн подчеркивает качество каждого изделия. Умная корзина, список желаний и интуитивная навигация создают безупречный опыт покупок. Каждая деталь интерфейса отражает философию бренда — сдержанную роскошь.',
    technologies: ['React', 'TypeScript', 'Context API', 'Tailwind CSS'],
    liveUrl: '#',
    duration: 5
  },
  { 
    id: '4', 
    title: "L'ÉPHÉMÈRE", 
    category: 'Restaurant', 
    year: '2025', 
    imageUrl: photo("lephemere.avif"),
    gallery: [photo("lephemere.avif"), photo("lephemere2.avif"), photo("lephemere3.avif"), photo("lephemere4.avif"), photo("lephemere5.avif"), photo("lephemere6.avif")],
    description: 'Эксклюзивный ресторан авангардной гастрономии',
    headline: 'Мультисенсорное цифровое пространство для ресторана, где каждое блюдо — произведение искусства.',
    fullDescription: 'Цифровое воплощение экспериментальной кухни. Каждый раздел сайта — это погружение в философию эфемерности: блюда, которые существуют лишь мгновение. Кастомный курсор, атмосферные звуковые ландшафты и AI-консьерж создают мультисенсорный опыт ещё до посещения ресторана.',
    technologies: ['React', 'Framer Motion', 'Web Audio API', 'Tailwind CSS'],
    liveUrl: '#',
    duration: 7
  },
  { 
    id: '5', 
    title: 'LIGHTER', 
    category: 'E-commerce', 
    year: '2025', 
    imageUrl: photo('lighter.avif'),
    gallery: [photo('lighter.avif'), photo('lighter2.avif'), photo('lighter3.avif'), photo('lighter4.avif'), photo('lighter5.avif'), photo('lighter6.avif'), photo('lighter7.avif'), photo('lighter8.avif'), photo('lighter9.avif'), photo('lighter10.avif')],
    description: 'Магазин современного умного освещения',
    headline: 'Полноценная e-commerce экосистема для бренда дизайнерского освещения.',
    fullDescription: 'Премиальный маркетплейс для дизайнерского освещения. Каталог с продвинутой фильтрацией, детальные страницы продуктов и лукбук вдохновения. Интегрированный блог и информативные страницы о доставке формируют полноценную экосистему бренда.',
    technologies: ['React', 'React Router', 'Context API', 'Tailwind CSS'],
    liveUrl: '#',
    duration: 6
  },
  { 
    id: '6', 
    title: 'LUMIÈRE ROASTERS', 
    category: 'Coffee Shop', 
    year: '2025', 
    imageUrl: photo('lumiereroasters.avif'),
    gallery: [photo('lumiereroasters.avif'), photo('lumiereroasters2.avif'), photo('lumiereroasters3.avif')],
    description: 'Артизанальная кофейня с AI-бариста',
    headline: 'Тёплая парижская эстетика и AI-бариста — цифровой дом для истинных ценителей кофе.',
    fullDescription: 'Цифровое пространство для истинных ценителей кофе. AI-бариста подбирает идеальный напиток на основе ваших предпочтений. Онлайн-магазин зерен, карта локаций и атмосфера парижских кофеен — всё в минималистичном, но тёплом дизайне с акцентами золотых тонов.',
    technologies: ['React', 'Lucide Icons', 'Tailwind CSS'],
    liveUrl: '#',
    duration: 4
  },
  { 
    id: '7', 
    title: 'METAL', 
    category: 'Music Platform', 
    year: '2025', 
    imageUrl: photo('metal.avif'),
    gallery: [photo('metal.avif'), photo('metal2.avif'), photo('metal3.avif'), photo('metal4.avif'), photo('metal5.avif'), photo('metal6.avif'), photo('metal7.avif'), photo('metal8.avif')],
    description: 'Музыкальная платформа для metalcore сообщества',
    headline: 'Агрессивная эстетика и неоновые акценты — платформа, передающая энергию тяжёлой музыки.',
    fullDescription: 'Энергичное приложение для фанатов тяжёлой музыки. Каталог артистов, трендовые треки, новости сцены и AI-раздел для персональных рекомендаций. Тёмная агрессивная эстетика с неоновыми акцентами передаёт энергию жанра. Виниловая коллекция и интерактивные опросы сообщества.',
    technologies: ['React', 'Gemini AI', 'Lucide Icons', 'Tailwind CSS'],
    liveUrl: '#',
    duration: 5
  },
  { 
    id: '8', 
    title: 'NOVABANK', 
    category: 'Fintech', 
    year: '2025', 
    imageUrl: photo('novabank.avif'),
    gallery: [photo('novabank.avif'), photo('novabank2.avif'), photo('novabank3.avif'), photo('novabank4.avif'), photo('novabank5.avif'), photo('novabank6.avif'), photo('novabank7.avif'), photo('novabank8.avif'), photo('novabank9.avif')],
    description: 'Современный fintech лендинг с AI-ассистентом',
    headline: 'Градиентная эстетика и микроанимации — fintech-лендинг, вызывающий доверие с первого взгляда.',
    fullDescription: 'Высокопроизводительная landing page для цифрового банка нового поколения. Вдохновлён Revolut и современными финтех-стартапами. AI-финансовый ассистент, мультиязычность, секции виртуальных карт, трейдинга и глобальных переводов. Градиентная эстетика и микроанимации создают ощущение надёжности и инновационности.',
    technologies: ['React', 'Gemini AI', 'i18n', 'Tailwind CSS'],
    liveUrl: '#',
    duration: 6
  },
  { 
    id: '9', 
    title: 'LUMOS ARCHITECTURE', 
    category: 'Architecture', 
    year: '2025', 
    imageUrl: photo('lumos.avif'),
    gallery: [photo('lumos.avif'), photo('lumos2.avif'), photo('lumos3.avif'), photo('lumos4.avif'), photo('lumos5.avif')],
    description: 'Платформа архитектурного бюро с 3D-визуализацией и AI-ассистентом',
    headline: 'Параметрическая графика и умный архитектор — цифровой twin студии современного проектирования.',
    fullDescription: 'LUMOS объединяет процедурную 3D-сцену, кинематографический свет и AI-консультанта, который говорит на языке архитекторов. Клиент погружается в эстетику студии ещё до первой встречи: интерактивная башня, советы по материалам и тонкое чувство пространства.',
    technologies: ['React', 'TypeScript', 'React Three Fiber', 'Gemini AI'],
    liveUrl: '#',
    duration: 7
  },
  { 
    id: '10', 
    title: 'NYC ATMOSPHERE', 
    category: 'City Experience', 
    year: '2025', 
    imageUrl: photo('nyc-atmosphere.avif'),
    gallery: [photo('nyc-atmosphere.avif'), photo('nyc-atmosphere2.avif'), photo('nyc-atmosphere3.avif'), photo('nyc-atmosphere4.avif'), photo('nyc-atmosphere5.avif'), photo('nyc-atmosphere6.avif'), photo('nyc-atmosphere7.avif'), photo('nyc-atmosphere8.avif'), photo('nyc-atmosphere9.avif'), photo('nyc-atmosphere10.avif')],
    description: 'Интерактивный гид по Нью-Йорку с AI-консьержем',
    headline: 'Видео-герой, неоновые переходы и AI-тревел-консьерж — погружение в город мечты.',
    fullDescription: 'Современный гид о Нью-Йорке с двуязычным контентом, видео-хиро и карточками районов. AI-консьерж на Gemini подбирает маршруты, гастро-точки и культурные события. Lazy loading, code splitting и адаптивные анимации обеспечивают плавный опыт на всех устройствах.',
    technologies: ['React', 'TypeScript', 'Tailwind CSS', 'Gemini AI'],
    liveUrl: '#',
    duration: 6
  },
  { 
    id: '11', 
    title: 'STELLAR VOYAGES', 
    category: 'Travel & Space', 
    year: '2025', 
    imageUrl: photo('stellar-voyages.avif'),
    gallery: [photo('stellar-voyages.avif'), photo('stellar-voyages1.avif'), photo('stellar-voyages2.avif')],
    description: 'Премиум сайт космического туризма с иммерсивными анимациями',
    headline: 'Путешествие к звёздам — luxury experience с параллаксом и 3D эффектами.',
    fullDescription: 'Современный сайт премиального космического туризма с захватывающими анимациями звёздного поля. Интерактивный исследователь направлений, многошаговая модальная система бронирования и продуманная типографика создают опыт высочайшего класса. Плавная прокрутка и стекломорфные элементы UI погружают пользователя в атмосферу космического путешествия.',
    technologies: ['React 19', 'TypeScript', 'Vite', 'CSS3'],
    liveUrl: '#',
    duration: 5
  },
  { 
    id: '12', 
    title: 'AETHERIA NEURAL ARCHITECTURE', 
    category: 'AI & Tech', 
    year: '2025', 
    imageUrl: photo('aetheria.avif'),
    gallery: [photo('aetheria.avif'), photo('aetheria1.avif'), photo('aetheria2.avif'), photo('aetheria3.avif'), photo('aetheria4.avif')],
    description: 'Нейронная архитектура и передовые AI-системы',
    headline: 'Архитектура будущего — визуализация сложных нейросетей в интерактивном формате.',
    fullDescription: 'Инновационная платформа, демонстрирующая возможности нейросетей и искусственного интеллекта. Интерактивные визуализации архитектуры сетей, демонстрация возможностей AI и современный дизайн создают впечатление технологичности и инноваций. Каждый элемент продуман для максимального погружения в мир передовых технологий.',
    technologies: ['React', 'TypeScript', 'Three.js', 'Tailwind CSS'],
    liveUrl: '#',
    duration: 6
  },
  { 
    id: '13', 
    title: 'AURA FRAGRANCES', 
    category: 'E-commerce', 
    year: '2025', 
    imageUrl: photo('aura.avif'),
    gallery: [photo('aura.avif'), photo('aura1.avif'), photo('aura2.avif'), photo('aura3.avif'), photo('aura4.avif'), photo('aura5.avif')],
    description: 'Премиальный магазин парфюмерии с AI-рекомендациями',
    headline: 'Элегантность ароматов — e-commerce парфюмерии с чувственным интерфейсом.',
    fullDescription: 'Изысканная платформа для ценителей парфюмерии. AI-консультант подбирает идеальный аромат на основе ваших предпочтений и особенностей. Галерея с описаниями нот, виртуальные тесты и атмосферный минималистичный дизайн создают роскошный опыт покупок. Каждая бутылка — произведение искусства в цифровом мире.',
    technologies: ['React', 'TypeScript', 'Tailwind CSS', 'Framer Motion'],
    liveUrl: '#',
    duration: 5
  },
  { 
    id: '14', 
    title: 'MATERIAL FORGE', 
    category: 'Manufacturing', 
    year: '2025', 
    imageUrl: photo('material-forge.avif'),
    gallery: [photo('material-forge.avif'), photo('material-forge1.avif'), photo('material-forge2.avif'), photo('material-forge3.avif'), photo('material-forge4.avif')],
    description: 'Платформа производства и инженерных решений',
    headline: 'Кузница инноваций — промышленный сайт с авангардным дизайном.',
    fullDescription: 'Платформа для промышленного производства и создания материалов будущего. Каталог инженерных решений, спецификации продуктов и интерактивные конфигураторы. Тёмный минималистичный дизайн с акцентами подчеркивает технологичность и профессионализм. 3D-модели материалов и интерактивные демонстрации.',
    technologies: ['React', 'TypeScript', 'Three.js', 'Tailwind CSS'],
    liveUrl: '#',
    duration: 6
  },
  { 
    id: '15', 
    title: 'MONOLITH STUDIO', 
    category: 'Digital Design', 
    year: '2025', 
    imageUrl: photo('monolith.avif'),
    gallery: [photo('monolith.avif'), photo('monolith1.avif'), photo('monolith2.avif'), photo('monolith3.avif'), photo('monolith4.avif')],
    description: 'Студия постоянных цифровых артефактов и PBR-визуализации',
    headline: 'Монолит дизайна — бруталистская эстетика в цифровом пространстве.',
    fullDescription: 'Цифровая студия, специализирующаяся на создании постоянных артефактов в цифровом пространстве. High-fidelity интерфейсные системы, физически-корректный рендеринг (PBR) и бруталистская философия дизайна. Портфолио проектов демонстрирует мастерство в создании твёрдых, вечных цифровых форм.',
    technologies: ['React', 'Tailwind CSS 4', 'PBR Rendering', 'Three.js'],
    liveUrl: '#',
    duration: 5
  },
  { 
    id: '16', 
    title: 'DIGITAL CANVAS', 
    category: 'Creative Platform', 
    year: '2025', 
    imageUrl: photo('digital-canvas.avif'),
    gallery: [photo('digital-canvas.avif'), photo('digital-canvas1.avif'), photo('digital-canvas2.avif'), photo('digital-canvas3.avif'), photo('digital-canvas4.avif')],
    description: 'Платформа цифрового искусства и творческого выражения',
    headline: 'Холст для творчества — платформа где каждый может быть художником.',
    fullDescription: 'Интерактивная платформа для цифровых художников и креативов. Встроенные инструменты для создания, галерея вдохновения и сообщество творцов. Плавные анимации, интуитивный интерфейс и поддержка различных форматов файлов делают её идеальной для самовыражения.',
    technologies: ['React', 'TypeScript', 'Canvas API', 'Tailwind CSS'],
    liveUrl: '#',
    duration: 5
  },
  { 
    id: '17', 
    title: 'XENON', 
    category: 'Robotics & AI', 
    year: '2025', 
    imageUrl: photo('xenon.avif'),
    gallery: [photo('xenon.avif'), photo('xenon1.avif'), photo('xenon2.avif')],
    description: 'Платформа синтетической жизни и продвинутой робототехники',
    headline: 'Вселенная Xenon — синтетическая жизнь и передовые роботические системы.',
    fullDescription: 'Инновационная платформа в области искусственной жизни и робототехники. Демонстрация возможностей синтетических организмов, интерактивные симуляции и исследовательские материалы. Авангардный дизайн с яркими акцентами отражает границы между естественным и искусственным.',
    technologies: ['React', 'TypeScript', 'Three.js', 'Tailwind CSS'],
    liveUrl: '#',
    duration: 5
  },
  { 
    id: '18', 
    title: 'ABYSSOS DEEP-SEA', 
    category: 'Interactive Art', 
    year: '2025', 
    imageUrl: photo('abyssos.avif'),
    gallery: [photo('abyssos.avif'), photo('abyssos1.avif'), photo('abyssos2.avif')],
    description: 'Интерактивная глубоководная экосистема с биолюминесцентными существами',
    headline: 'Глубины неизведанного — погружение в магический мир биолюминесценции.',
    fullDescription: 'Ультрасовременная интерактивная инсталляция, воссоздающая атмосферу глубокого океана. Канвас-анимация создаёт школы рыб, медуз, кальмаров и прочих глубоководных существ с эффектом свечения. Динамическая глубина, взаимодействие с мышью и плавные переходы создают мультисенсорный опыт погружения в неизведанные глубины морей.',
    technologies: ['React', 'Canvas API', 'TypeScript', 'Tailwind CSS'],
    liveUrl: '#',
    duration: 4
  },
  { 
    id: '19', 
    title: 'JITTER', 
    category: 'Animation & Motion', 
    year: '2025', 
    imageUrl: photo('jitter.avif'),
    gallery: [photo('jitter.avif'), photo('jitter1.avif'), photo('jitter2.avif'), photo('jitter3.avif')],
    description: 'Платформа анимации и эффектов движения',
    headline: 'Движение это жизнь — платформа для создания динамичных интерфейсов.',
    fullDescription: 'Инновационная платформа для работы с анимациями и эффектами движения.库инструменты для создания плавных переходов, интерактивных элементов и кинематографических эффектов. Оптимизированная для производительности, с поддержкой GPU-ускорения и встроенными библиотеками анимаций.',
    technologies: ['React', 'TypeScript', 'Vite', 'ESLint', 'Tailwind CSS'],
    liveUrl: '#',
    duration: 5
  },
  { 
    id: '20', 
    title: 'ZENITH-TYPE', 
    category: 'Typography & Design', 
    year: '2025', 
    imageUrl: photo('zenith-type.avif'),
    gallery: [photo('zenith-type.avif'), photo('zenith-type1.avif'), photo('zenith-type2.avif'), photo('zenith-type3.avif')],
    description: 'Сервис типографии и дизайна шрифтов',
    headline: 'Вершина типографии — каждая буква имеет значение.',
    fullDescription: 'Передовая платформа для исследования, выбора и применения типографики в дизайне. Более 1000 шрифтов, инструменты для кастомизации, интерактивные примеры использования. Помогает дизайнерам создавать визуальную иерархию, улучшающую читаемость и эстетику интерфейсов. Полная поддержка варьируемых шрифтов и OpenType функций.',
    technologies: ['React', 'TypeScript', 'Vite', 'Tailwind CSS'],
    liveUrl: '#',
    duration: 5
  }
];

export const showcaseProjects = allProjects.slice(0, 3);
